#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""麦蕊 Python SDK 全接口调阅 Demo。证书：环境变量 MAIRUI_LICENCE。"""
from __future__ import annotations

import json
import os
import sys
import time

try:
    from mairui import Client
except ImportError:
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))
    from mairui import Client

ALLOW_SKIP = frozenset({'stock_vip_history'})
PREVIEW = 280
QUIET = os.environ.get('MAIRUI_DEMO_QUIET', '').strip() in {'1', 'true', 'yes'}

# 请填写你自己的证书 UUID（也可改用环境变量 MAIRUI_LICENCE）。切勿提交真实证书到公开仓库。
LICENCE = ""

def preview(data) -> str:
    try:
        s = json.dumps(data, ensure_ascii=False, default=str)
    except Exception:
        s = str(data)
    s = s.replace('\n', ' ')
    return s if len(s) <= PREVIEW else s[:PREVIEW] + '...'

def main() -> int:
    lic = os.environ.get('MAIRUI_LICENCE', '').strip() or LICENCE.strip()
    if not lic:
        print('请填写证书：设置环境变量 MAIRUI_LICENCE，或编辑本文件顶部 LICENCE = "你的证书UUID"')
        return 1
    api = Client(licence=lic, max_retries=2, timeout=(5, 90))
    results = []

    def run(name, fn):
        t0 = time.time()
        try:
            data = fn()
            n = len(data) if hasattr(data, '__len__') and not isinstance(data, (str, bytes)) else 1
            ms = int((time.time() - t0) * 1000)
            results.append({'name': name, 'ok': True, 'n': n, 'ms': ms})
            if not QUIET:
                print(f'OK   {name}  n={n}  {ms}ms  {preview(data)}')
        except Exception as e:
            err = str(e)
            ms = int((time.time() - t0) * 1000)
            skip = name in ALLOW_SKIP and any(x in err for x in ('404', '104', '资源不存在'))
            results.append({'name': name, 'ok': False, 'skip': skip, 'err': err[:300], 'ms': ms})
            if not QUIET:
                print(f"{'SKIP' if skip else 'FAIL'} {name}  {ms}ms  {err[:120]}")

    run('stock_list', lambda: api.stock_list())
    run('new_stock_calendar', lambda: api.new_stock_calendar())
    run('sectors_list', lambda: api.sectors_list())
    run('primary_sectors_list', lambda: api.primary_sectors_list())
    run('sector_detail', lambda: api.sector_detail("GN玻璃"))
    run('stock_history', lambda: api.stock_history("000001.SZ", "d", "n", st="20240101", et="20241231", lt=1))
    run('stock_latest', lambda: api.stock_latest("000001.SZ", "d", "n", lt=1))
    run('stock_vip_history', lambda: api.stock_vip_history("000001.SZ", "d", "n", st="20240101", et="20241231", lt=1))
    run('stock_stopprice', lambda: api.stock_stopprice("000001.SZ", lt=1))
    run('stock_indicators', lambda: api.stock_indicators("000001.SZ", lt=1))
    run('stock_indicator', lambda: api.stock_indicator("macd", "000001.SZ", "d", "n", lt=1))
    run('stock_macd', lambda: api.stock_macd("000001.SZ", "d", "n", lt=1))
    run('stock_ma', lambda: api.stock_ma("000001.SZ", "d", "n", lt=1))
    run('stock_boll', lambda: api.stock_boll("000001.SZ", "d", "n", lt=1))
    run('stock_kdj', lambda: api.stock_kdj("000001.SZ", "d", "n", lt=1))
    run('stock_real_time', lambda: api.stock_real_time("000001"))
    run('stock_real_five', lambda: api.stock_real_five("000001"))
    run('stock_ssjy', lambda: api.stock_ssjy("000001"))
    run('stock_ssjy_all', lambda: api.stock_ssjy_all())
    run('stock_real_all', lambda: api.stock_real_all())
    run('stock_ssjy_more', lambda: api.stock_ssjy_more(["000001","600519"]))
    run('stock_zbjy', lambda: api.stock_zbjy("000001"))
    run('stock_transaction', lambda: api.stock_transaction("000001.SZ", lt=1))
    run('stock_financial', lambda: api.stock_financial("balance", "000001.SZ", lt=1))
    run('stock_balance', lambda: api.stock_balance("000001.SZ", lt=1))
    run('stock_income', lambda: api.stock_income("000001.SZ", lt=1))
    run('stock_cashflow', lambda: api.stock_cashflow("000001.SZ", lt=1))
    run('stock_pershareindex', lambda: api.stock_pershareindex("000001.SZ", lt=1))
    run('stock_capital', lambda: api.stock_capital("000001.SZ", lt=1))
    run('stock_shareholder_count', lambda: api.stock_shareholder_count("000001.SZ", lt=1))
    run('stock_top_holders', lambda: api.stock_top_holders("000001.SZ", lt=1))
    run('stock_flow_holders', lambda: api.stock_flow_holders("000001.SZ", lt=1))
    run('stock_instrument', lambda: api.stock_instrument("000001.SZ"))
    run('company', lambda: api.company("gsjj", "000001"))
    run('company_profile', lambda: api.company_profile("000001"))
    run('company_indexes', lambda: api.company_indexes("000001"))
    run('company_directors', lambda: api.company_directors("000001"))
    run('company_executives', lambda: api.company_executives("000001"))
    run('company_supervisors', lambda: api.company_supervisors("000001"))
    run('company_top10_holders', lambda: api.company_top10_holders("000001"))
    run('company_top10_float_holders', lambda: api.company_top10_float_holders("000001"))
    run('company_holder_change', lambda: api.company_holder_change("000001"))
    run('company_dividends', lambda: api.company_dividends("000001"))
    run('company_seo', lambda: api.company_seo("000001"))
    run('company_unlock', lambda: api.company_unlock("000001"))
    run('company_fund_holding', lambda: api.company_fund_holding("000001"))
    run('company_earnings_forecast', lambda: api.company_earnings_forecast("000001"))
    run('company_financial_index', lambda: api.company_financial_index("000001"))
    run('company_quarter_profit', lambda: api.company_quarter_profit("000001"))
    run('company_quarter_cashflow', lambda: api.company_quarter_cashflow("000001"))
    run('stock_pool', lambda: api.stock_pool("ztgc", "2026-01-15"))
    run('limit_up_pool', lambda: api.limit_up_pool("2026-01-15"))
    run('limit_down_pool', lambda: api.limit_down_pool("2026-01-15"))
    run('strong_pool', lambda: api.strong_pool("2026-01-15"))
    run('new_stock_pool', lambda: api.new_stock_pool("2026-01-15"))
    run('broken_board_pool', lambda: api.broken_board_pool("2026-01-15"))
    run('concept_tree', lambda: api.concept_tree())
    run('concepts_of_stock', lambda: api.concepts_of_stock("000001"))
    run('stocks_of_concept', lambda: api.stocks_of_concept("sw_mt"))
    run('stock_interactiveqa', lambda: api.stock_interactiveqa("000001.SZ", lt=1))
    run('stock_announcement', lambda: api.stock_announcement("000001.SZ", lt=1))
    run('index_list', lambda: api.index_list())
    run('index_history', lambda: api.index_history("000001.SH", "d", lt=1))
    run('index_latest', lambda: api.index_latest("000001.SH", "d", lt=1))
    run('index_indicator', lambda: api.index_indicator("macd", "000001.SH", "d", lt=1))
    run('index_macd', lambda: api.index_macd("000001.SH", "d", lt=1))
    run('index_ma', lambda: api.index_ma("000001.SH", "d", lt=1))
    run('index_boll', lambda: api.index_boll("000001.SH", "d", lt=1))
    run('index_kdj', lambda: api.index_kdj("000001.SH", "d", lt=1))
    run('index_real_time', lambda: api.index_real_time("000001.SH"))
    run('bj_stock_list', lambda: api.bj_stock_list())
    run('bj_index_list', lambda: api.bj_index_list())
    run('bj_stock_real_time', lambda: api.bj_stock_real_time("920000.BJ"))
    run('bj_stock_real_five', lambda: api.bj_stock_real_five("920000.BJ"))
    run('bj_index_real_time', lambda: api.bj_index_real_time("899050"))
    run('bj_history', lambda: api.bj_history("920000.BJ", "d", "n", lt=1))
    run('bj_financial', lambda: api.bj_financial("balance", "920000.BJ", lt=1))
    run('bj_balance', lambda: api.bj_balance("920000.BJ", lt=1))
    run('bj_income', lambda: api.bj_income("920000.BJ", lt=1))
    run('bj_cashflow', lambda: api.bj_cashflow("920000.BJ", lt=1))
    run('bj_pershareindex', lambda: api.bj_pershareindex("920000.BJ", lt=1))
    run('bj_capital', lambda: api.bj_capital("920000.BJ", lt=1))
    run('bj_shareholder_count', lambda: api.bj_shareholder_count("920000.BJ", lt=1))
    run('bj_top_holders', lambda: api.bj_top_holders("920000.BJ", lt=1))
    run('bj_flow_holders', lambda: api.bj_flow_holders("920000.BJ", lt=1))
    run('fund_list', lambda: api.fund_list())
    run('etf_list', lambda: api.etf_list())
    run('fund_real_time', lambda: api.fund_real_time("510300"))
    run('star_stock_list', lambda: api.star_stock_list())
    run('star_real_time', lambda: api.star_real_time("688001"))
    run('star_real_five', lambda: api.star_real_five("688001"))
    run('fundc_pm_kfpm', lambda: api.fundc_pm_kfpm())
    run('fundc_pm_fbpm', lambda: api.fundc_pm_fbpm())
    run('fundc_pm_fzyj', lambda: api.fundc_pm_fzyj())
    run('fundc_other_jjzc', lambda: api.fundc_other_jjzc("2026_2"))
    run('fundc_other_zcbd', lambda: api.fundc_other_zcbd("2026_2"))
    run('fundc_other_dxjg', lambda: api.fundc_other_dxjg())
    run('fundc_pm_kfjzg', lambda: api.fundc_pm_kfjzg())
    run('fundc_pm_kfjzq', lambda: api.fundc_pm_kfjzq())
    run('fundc_pm_fbjz', lambda: api.fundc_pm_fbjz())
    run('fundc_jf_kffh', lambda: api.fundc_jf_kffh())
    run('fundc_jf_fzfh', lambda: api.fundc_jf_fzfh())
    run('fundc_gm_kfgm', lambda: api.fundc_gm_kfgm())
    run('fundc_gm_fbgm', lambda: api.fundc_gm_fbgm())
    run('fundc_gm_fzgm', lambda: api.fundc_gm_fzgm())
    run('fundf10_lsjz', lambda: api.fundf10_lsjz("000001"))
    run('fundf10_fhps', lambda: api.fundf10_fhps("000001"))
    run('fundf10_jdtj', lambda: api.fundf10_jdtj("000001"))
    run('fundf10_jdzfmx', lambda: api.fundf10_jdzfmx("000001"))
    run('fundf10_jjgk', lambda: api.fundf10_jjgk("000001"))
    run('fundf10_jjyj', lambda: api.fundf10_jjyj("000001"))
    run('fundf10_jjfh', lambda: api.fundf10_jjfh("000001"))
    run('fundf10_jjgm', lambda: api.fundf10_jjgm("000001"))
    run('fundf10_gzlb', lambda: api.fundf10_gzlb())
    run('fundf10_pzzzgz', lambda: api.fundf10_pzzzgz("000001"))
    run('fundf10_hqzksjz', lambda: api.fundf10_hqzksjz("000001"))
    run('fundf10_all', lambda: api.fundf10_all())
    run('fundf10_zrjl', lambda: api.fundf10_zrjl())
    run('fundf10_fbs', lambda: api.fundf10_fbs())
    run('fundf10_etf', lambda: api.fundf10_etf())
    run('fundf10_lof', lambda: api.fundf10_lof())
    run('fundf10_gpcc', lambda: api.fundf10_gpcc("000001"))
    run('fundf10_zqcc', lambda: api.fundf10_zqcc("000001"))
    run('fundf10_hypz', lambda: api.fundf10_hypz("000001"))
    run('fundf10_zcpz', lambda: api.fundf10_zcpz("000001"))
    run('fundf10_gmbd', lambda: api.fundf10_gmbd("000001"))
    run('fundf10_cyrjg', lambda: api.fundf10_cyrjg("000001"))
    run('hsdc_jlr', lambda: api.hsdc_jlr())
    run('hsdc_jlrl', lambda: api.hsdc_jlrl())
    run('hsdc_zljlr', lambda: api.hsdc_zljlr())
    run('hsdc_zljlrl', lambda: api.hsdc_zljlrl())
    run('hsdc_shzlr', lambda: api.hsdc_shzlr())
    run('hsdc_shjlrl', lambda: api.hsdc_shjlrl())
    run('hsdc_nbzj_lxgl', lambda: api.hsdc_nbzj_lxgl())
    run('hsdc_nbzj_bxls', lambda: api.hsdc_nbzj_bxls("1"))
    run('hsdc_nbzj_nxls', lambda: api.hsdc_nbzj_nxls("1"))
    run('hsdc_nbzj_bxzl', lambda: api.hsdc_nbzj_bxzl())
    run('hsdc_nbzj_nxzl', lambda: api.hsdc_nbzj_nxzl())
    run('hsdc_nbzj_hgtc', lambda: api.hsdc_nbzj_hgtc())
    run('hsdc_nbzj_sgtc', lambda: api.hsdc_nbzj_sgtc())
    run('hsdc_nbzj_ggth', lambda: api.hsdc_nbzj_ggth())
    run('hsdc_nbzj_ggts', lambda: api.hsdc_nbzj_ggts())
    run('hsdc_nbzj_ah', lambda: api.hsdc_nbzj_ah())
    run('hsdc_nbzj_hgts', lambda: api.hsdc_nbzj_hgts())
    run('hsdc_nbzj_sgts', lambda: api.hsdc_nbzj_sgts())
    run('hsdc_nbzj_hcjd', lambda: api.hsdc_nbzj_hcjd())
    run('hsdc_nbzj_scjd', lambda: api.hsdc_nbzj_scjd())
    run('hsdc_nbzj_bxpm', lambda: api.hsdc_nbzj_bxpm("D"))
    run('hsdc_nbzj_hgpm', lambda: api.hsdc_nbzj_hgpm("D"))
    run('hsdc_nbzj_sgpm', lambda: api.hsdc_nbzj_sgpm("D"))
    run('hsdc_nbzj_hgls', lambda: api.hsdc_nbzj_hgls())
    run('hsdc_nbzj_shls', lambda: api.hsdc_nbzj_shls())
    run('hsdc_nbzj_ghls', lambda: api.hsdc_nbzj_ghls())
    run('hsdc_nbzj_gsls', lambda: api.hsdc_nbzj_gsls())
    run('hsdc_list', lambda: api.hsdc_list())
    run('hsdc_comparison', lambda: api.hsdc_comparison())
    run('hsdc_spot', lambda: api.hsdc_spot())
    run('hsdc_himk_jdzgzd', lambda: api.hsdc_himk_jdzgzd())
    run('hsdc_himk_pzxg', lambda: api.hsdc_himk_pzxg())
    run('hsdc_himk_pzxd', lambda: api.hsdc_himk_pzxd())
    run('hsdc_himk_cjzz', lambda: api.hsdc_himk_cjzz())
    run('hsdc_himk_cjzj', lambda: api.hsdc_himk_cjzj())
    run('hsdc_himk_lxfl', lambda: api.hsdc_himk_lxfl())
    run('hsdc_himk_lxsl', lambda: api.hsdc_himk_lxsl())
    run('hsdc_himk_lxsz', lambda: api.hsdc_himk_lxsz())
    run('hsdc_himk_lxxd', lambda: api.hsdc_himk_lxxd())
    run('hsdc_himk_zzd', lambda: api.hsdc_himk_zzd())
    run('hsdc_himk_yzd', lambda: api.hsdc_himk_yzd())
    run('hsdc_himk_zqsg', lambda: api.hsdc_himk_zqsg())
    run('hsdc_himk_mqsg', lambda: api.hsdc_himk_mqsg())
    run('hsdc_himk_ltszph', lambda: api.hsdc_himk_ltszph())
    run('hsdc_himk_syl', lambda: api.hsdc_himk_syl())
    run('hsdc_himk_sjl', lambda: api.hsdc_himk_sjl())
    run('hsdc_himk_roe', lambda: api.hsdc_himk_roe())
    run('hsdc_jrts', lambda: api.hsdc_jrts())
    run('hsdc_rzrqzl', lambda: api.hsdc_rzrqzl())
    run('hsdc_rzrqmx', lambda: api.hsdc_rzrqmx())
    run('hsdc_dzjy', lambda: api.hsdc_dzjy())
    run('hsdc_jjxs', lambda: api.hsdc_jjxs())
    run('hsdc_dxsy', lambda: api.hsdc_dxsy())
    run('hsdc_lsfh', lambda: api.hsdc_lsfh())
    run('hsdc_hibk_zjhhy', lambda: api.hsdc_hibk_zjhhy())
    run('hsdc_hibk_gnbk', lambda: api.hsdc_hibk_gnbk())
    run('hsdc_hicw_lr', lambda: api.hsdc_hicw_lr())
    run('hsdc_zjh', lambda: api.hsdc_zjh())
    run('hsdc_bk', lambda: api.hsdc_bk())
    run('hsdc_ggzl', lambda: api.hsdc_ggzl())
    run('hsdc_lxlr', lambda: api.hsdc_lxlr())
    run('hsdc_hilh_mrxq', lambda: api.hsdc_hilh_mrxq())
    run('hsdc_hilh_xwmx', lambda: api.hsdc_hilh_xwmx())
    run('factor_valuation', lambda: api.factor_valuation("000001"))
    run('factor_quality', lambda: api.factor_quality("000001"))
    run('factor_growth', lambda: api.factor_growth("000001"))
    run('factor_momentum', lambda: api.factor_momentum("000001"))
    run('factor_capital', lambda: api.factor_capital("000001"))
    run('factor_signal', lambda: api.factor_signal("000001"))
    run('factor_risk', lambda: api.factor_risk("000001"))
    run('factor_dividend', lambda: api.factor_dividend("000001"))
    run('factor_scale', lambda: api.factor_scale("000001"))
    run('factor_sentiment', lambda: api.factor_sentiment("000001"))
    run('factor_all', lambda: api.factor_all("000001"))
    run('factor_list', lambda: api.factor_list())
    run('factor_categories', lambda: api.factor_categories())
    run('factor_rank', lambda: api.factor_rank("valuation"))
    run('factor_top', lambda: api.factor_top("valuation", "000001"))
    run('factor_history', lambda: api.factor_history("valuation", "000001"))
    run('factor_percentile', lambda: api.factor_percentile("valuation", "000001"))

    api.close()
    fail = [r for r in results if not r.get('ok') and not r.get('skip')]
    skip = [r for r in results if r.get('skip')]
    ok = len(results) - len(fail) - len(skip)
    summary = {'total': len(results), 'ok': ok, 'fail': len(fail), 'skip': len(skip)}
    print(json.dumps(summary, ensure_ascii=False))
    if fail:
        print('fails:', json.dumps(fail, ensure_ascii=False)[:2000])
        return 2
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
